name: Create Tag
on:
  push:
    branch: [ main ]
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set Version
        run: echo "VERSION=$(make version)" >> $GITHUB_ENV

      - uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ env.VERSION }}
          message: "Automated tag"
